import { Task } from './task';

export const TASKS: Task[] = [
  { id: 1, name: 'Task 1', lectureTitle: 'CSS Frameworks', lecturerName: 'Yuriy Dzhavala', description: 'A CSS framework is a pre-prepared software framework that is meant to allow for easier, more standards-compliant web design using the Cascading Style Sheets language. Most of these frameworks contain at least a grid'},
  { id: 2, name: 'Task 2', lectureTitle: 'OOP', lecturerName: 'Vasyl Motsyak', description: 'Object-oriented programming is a programming paradigm based on the concept of "objects", which may contain data, in the form of fields, often known as attributes; and code, in the form of procedures, often known as methods' },
  { id: 3, name: 'Task 3', lectureTitle: 'ES Next', lecturerName: 'Bohdan Lobor', description: 'ECMAScript is a trademarked scripting-language specification standardized by Ecma International in ECMA-262 and ISO/IEC 16262. It was created to standardize JavaScript, so as to foster multiple independent implementations' },
  { id: 4, name: 'Task 4', lectureTitle: 'AJAX', lecturerName: 'Mykyta Morachov', description: 'Ajax is a set of Web development techniques using many Web technologies on the client side to create asynchronous Web applications. With Ajax, Web applications can send and retrieve data from a server asynchronously without interfering with the display and behavior of the existing page' },
  { id: 5, name: 'Task 5', lectureTitle: 'Webpack', lecturerName: 'Orest Soroka', description: 'Webpack is an open-source JavaScript module bundler. Its main purpose is to bundle JavaScript files for usage in a browser, yet it is also capable of transforming, bundling, or packaging just about any resource or asset. Webpack takes modules with dependencies and generates static assets representing those modules' },
  { id: 6, name: 'Task 6', lectureTitle: 'JS Patterns', lecturerName: 'Yevhen Lysyakov', description: 'Design patterns are reusable solutions to commonly occurring problems in software design. They are both exciting and a fascinating topic to explore in any programming language.' },
  { id: 7, name: 'Task 7', lectureTitle: 'Architectural Patterns', lecturerName: 'Yura Shkoropad', description: 'It is a general, reusable solution to a commonly occurring problem in software architecture within a give context. Architectural patterns are similar to software design pattern but have a broader scope.' },
  { id: 8, name: 'Task 8', lectureTitle: 'React.js/JSX', lecturerName: 'Roman Mahotskyi', description: 'In computing, React is a JavaScript library for building user interfaces. It is maintained by Facebook and a community of individual developers and companies. React can be used as a base in the development of single-page or mobile applications' },
  { id: 9, name: 'Task 9', lectureTitle: 'Angular', lecturerName: 'Kostiantyn Kubusha and Ihor Silantiev', description: 'Angular is a TypeScript-based open-source front-end web application platform led by the Angular Team at Google and by a community of individuals and corporations' },
  { id: 10, name: 'Task 10', lectureTitle: 'NodeJS/ExpressJS', lecturerName: 'Yuriy Teslenko', description: 'Node.js is an open-source, cross-platform JavaScript run-time environment that executes JavaScript code outside of a browser.' }
];
